<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd â€¦">
<plist version="1.0">
<dict>
<key>items</key>
<array>
<dict>
<key>assets</key>
<array>
<dict>
<key>kind</key>
<string>software-package</string>
<key>url</key>
<string>https://korashoot.online/aplication/Snake.io+.ipa</string>
</dict>
<dict>
<key>kind</key>
<string>display-image</string>
<key>url</key>
<string>https://kurd4u.com/photo/snakeio</string>
</dict>
<dict>
<key>kind</key>
<string>full-size-image</string>
<key>url</key>
<string>https://kurd4u.com/photo/snakeio</string>
</dict>
</array>
<key>metadata</key>
<dict>
<key>bundle-identifier</key>
<string>com.kooapps.snakearcade</string>
<key>bundle-version</key>
<string>1.1.4</string>
<key>kind</key>
<string>software</string>
<key>title</key>
<string>Snake.io</string>
</dict> 
</dict>
</array>
</dict>
</plist>